### ISSUE TITLE
Bug: Duplicated injectables

### ISSUE THREAD

**Issue by kamilkisiela** [pbastowski/angular2-now#34]
When decorator's target has the same injectable (in target.$inject) as one of these provided by @Inject() decorator it will be duplicated. It's on meteor1.2 branch (probably on the others also).

Am I wrong or duplicates should be removed?

If so, I'm going to fix it on my branch with unit-tests.

**Comment by pbastowski** [comment]
I don't expect `target.$inject` to have anything added there by the user. That's what `@Inject` is for, but, I suppose the user could manually push/unshift into `target.$inject`. 

Come to think of it, in my defer-controller-3-decorate branch I do `unshift` $scope into $inject, because I don't know if it's already there. So, I need the ability to have duplicated services in $inject under certain circumstances.

So, it is not an error to have duplicate injectables. But it could be a bit silly at times.

**Comment by kamilkisiela** [comment]
Oh, I see :)
