### ISSUE TITLE
MeteorReactive is not a function

### ISSUE THREAD

**Issue by tuvokki** [pbastowski/angular2-now#47]
Hi, I'm trying to use the MeteorReactive annotation referenced in #41 but I get an error stating:

```
Uncaught TypeError: MeteorReactive is not a function
```

I looked up the actual code and it is (indeed) not in the `./.meteor/local/build/programs/web.browser/packages/pbastowski_angular2-now.js` file that gets generated when I start my application. In my versions file I see that I am using `pbastowski:angular2-now@1.0.2` (which is the version installed when I do `meteor add pbastowski:angular2-now`).

How can I use the latest version that includes the annotation I want?

FWIW the aforementioned annotation is also used in the socially titurial app which is also not working for me. see: https://github.com/Urigo/meteor-angular-socially/blob/master/client/socially/socially.component.js

**Comment by pbastowski** [comment]
The reason you can't use this decorator is because it is not yet merged into the release branch or published on atmospherejs.com. The reason behind that is that it has not been tested thoroughly enough yet.

There is, however, a way you can use this new feature while at the same time helping with the testing. To do this `git clone` angular2-now `https://github.com/pbastowski/angular2-now.git` into your `packages` folder an then `git checkout` branch `feature/defer-controller-3-decorate`. Let me know if you need further instructions on how to do this.

Thanks for letting me know about the tutorial already mentioning this new feature.

**Comment by tuvokki** [comment]
Thanks for the info. I kinda figured it out an am running it in my local workspace now. I'll do some testing (but I'm kinda a meteor noob so it might not be worth a lot).

While we're at it, I tried to use the `@Input()` annotation, but there is no support for that yet, right? I tried using to pass data into a component directive.

**Comment by pbastowski** [comment]
That's correct, there is no support for `@Input`. If you need very comprehensive Angular2 support for your Angular1 projects, then you might want to have a look at `ng-forward`. That library is a lot bigger in size and more complex, but also supports more features, if that's what you need.

**Comment by tuvokki** [comment]
Thanks for the tip. For now I probably can work around it, otherwise I'll take a look at `ng-forward`. If I have any more feedback I'll let you know.
